### PR TITLE
Sig Parsing Refactor

### PR DESCRIPTION
**Pull request by gvillafanetapia**
New parser refactored by Mutt Data team.

We'll have to validate how we can integrate with the current code and replace the old parser.

Let us know if you want us to do any changes, or where do you think this logic should be placed.

### CODE REVIEW

**Comment by thehandcoder** [comment]
@akircher Just giving this a look over and had a couple of comments.

* Should the Class be moved into the GoodPill namespace?
* Should the functions be moved into classes or into appropriate helper files?
* There are no DocBlocks on the methods and properties in the Parser class.

**Comment by thehandcoder** [comment]
@akircher One other thing.  We use composer to manage all of our other dependencies.  Is ComprehendMedical available as part of the aws compser packages.

**Comment by thehandcoder** [comment]
@akircher It appears it is https://github.com/aws/aws-sdk-php/blob/master/src/ComprehendMedical/ComprehendMedicalClient.php

It's already install and available as part of our composer autoloader.  We also have constants defined for the AWS credentials.

AWS_KEY
AWS_SECRET
AWS_REGION

**Comment by akircher** [comment]
I think you are right on all of these.  I will hold off on doing the merge.

I think it will be more efficient for you to manage these changes. Can you
coordinate having mutt data make any/all of these changes or if you want
Jesse or yourself to do some of them yourselves.

You will also note that while our current parser returns sig_qty_per_day,
this one returns sig_qty and sig_days, so you would need to divide them in
order to compare it to our current parser.

**Comment by gvillafanetapia** [comment]
Hi Ben, 

1. @JDSanto will get on to improving the documentation.
2. 👌 with the AWS dependencies
3. Checking the project it looked like it would be best to move this into  `Classes/GoodPill` and add the corresponding namespaces but whatever you think its best.. let us know.

**Comment by JDSanto** [comment]
Hello Ben. I've added DocBlocks to the methods and attributes for the SigParser class. If anything looks wrong with the format let me know

**Comment by thehandcoder** [comment]
Hey @gvillafanetapia and @JDSanto ,

I saw the updates from  .  They look good, but there are still a few questions. 

1. The file should be moved to the classes folder.  I'd suggest classes/GoodPill/Utilities.  We also need to add the namespace GoodPill\Utilities
2. Is there a reason the preprocessing() is broken into a function instead of a method on the SigParser class?  I'd prefer if we stuck with Object based as much as possible.  
3. It looks like the test file probably needs to be updated as well.  We already have the AWS library available via composer and our own include.  The vendor include file is `require_once 'vendor/autoload.php';`
4. You should move your test files into the testing folder.  You will probably also want to add the following lines to your test script so all of the php includes can be found.  
```
ini_set('memory_limit', '512M');
ini_set('include_path', '/goodpill/webform');
date_default_timezone_set('America/New_York');
```

If you get these updated, I can merge these files and add them beside our current parser so we can compare the outputs in realtime.

**Comment by JDSanto** [comment]
Hello Ben. I've made the changes based on your feedback, and also added the AWS credentials constants to use the Comprehend Medical Client

**Pull request merged**
