### PR TITLE
#zthwxx - Add Translations to Events

### PR DESCRIPTION
**Pull request by Hobstweedl**
- adds a `setLanguage` function that takes in a GpPatient model and add's the patient's language to the comms arrays
Example usage
- This could be rewritten to take in just the language code `EN`, `ES`, `FR` ect but then the logic to uppercase and only add it to the language property if it isn't english would need to be manually handled in each case

```
    public function getEmail() : ?EmailComm
    {
        $email              = new EmailComm();
        $email->subject     = $this->render('email_subject');
        $email->message     = $this->render('email');
        $email->email       = $this->patient->email;

        $email->setLanguage($this->patient);

        return $email;
    }

### CODE REVIEW

**Comment by thehandcoder** [comment]
Task linked: [CU-zthwxx Add Spanish functions to new communication template classes](https://app.clickup.com/t/zthwxx)

**Review by thehandcoder — CHANGES_REQUESTED** [review]
I see you've added a setLanguage onto these 2 objects, but where does this language actually get added.  I only see the changes to add the setLanguage, but I don't see anywhere in the code that actually calls these methods.

**Comment by Hobstweedl** [comment]
@thehandcoder I didn't add the code to any existing events because I was not sure which ones were currently being used and if this should be applied to them. I can add it to the OrderEvent and the CarepointLabelChanged event in this PR and that should cover all of the current events

**Comment by Hobstweedl** [comment]
Looks like the CarepointLabelChanged event doesn't send email or text, so adding the language to the Order Event should cover all other events since they inherit the Order Event

**Review by thehandcoder — APPROVED** [review]

**Pull request merged**
